[Variables]

; Save this text file and refresh the skin after editing these settings!

Bands=80
; Number of raindrops
; Activate the GenerateBands.ini file after changing this value

BarWidth=1
; Raindrop width

BarHeight=175
; Maximum raindrop height

BarGap=24
; Spacing between the raindrops

Color=128,160,255
; Don't add an alpha value at the end

RainSpeed=80
; Rainfall speed

RainConstant=3
; Rainfall speed when no sound is playing

RainCover=#WORKAREAHEIGHT#
; Rainfall height

AverageSize=5
; Number of past measure values to average from, increasing continuity

Port=Output
ID=""
FFTSize=9216
FFTOverlap=(#FFTSize#*0.5)
FFTAttack=0
FFTDecay=250
FreqMin=20
FreqMax=16000
Sensitivity=35
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel

; Context menu environment variables
Config=Rainy Days
ConfigPath=C:\Users\YourName\My Documents\Rainmeter\Skins\Rainy Days\Rainy Days.ini
