[Variables]
BarWidth=1
BarHeight=(#WORKAREAHEIGHT#/32)
BarGapX=12R
BarGapY=0
BarOrientation=Vertical

FFTAttack=350
FFTDecay=350
FFTSize=2048
FreqMin=40
FreqMax=16000
; Audio settings
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel#FFTOptions

MeasureName=MeasureAudioRepeat
MeterName=MeterBarRepeat

Bands=128
Sensitivity=42

Color=161,186,220,255

Angle=270
RainSpeed=100
RainConstant=1
RainCover=#WORKAREAHEIGHT#