[MeasureAudio1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1
; AverageSize=#Fluidity#

[MeterBar1]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio1

[MeasureAudio2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2
; AverageSize=#Fluidity#

[MeterBar2]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio2

[MeasureAudio3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3
; AverageSize=#Fluidity#

[MeterBar3]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio3

[MeasureAudio4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4
; AverageSize=#Fluidity#

[MeterBar4]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio4

[MeasureAudio5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5
; AverageSize=#Fluidity#

[MeterBar5]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio5

[MeasureAudio6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6
; AverageSize=#Fluidity#

[MeterBar6]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio6

[MeasureAudio7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7
; AverageSize=#Fluidity#

[MeterBar7]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio7

[MeasureAudio8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8
; AverageSize=#Fluidity#

[MeterBar8]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio8

[MeasureAudio9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9
; AverageSize=#Fluidity#

[MeterBar9]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio9

[MeasureAudio10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10
; AverageSize=#Fluidity#

[MeterBar10]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio10

[MeasureAudio11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11
; AverageSize=#Fluidity#

[MeterBar11]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio11

[MeasureAudio12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12
; AverageSize=#Fluidity#

[MeterBar12]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio12

[MeasureAudio13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13
; AverageSize=#Fluidity#

[MeterBar13]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio13

[MeasureAudio14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14
; AverageSize=#Fluidity#

[MeterBar14]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio14

[MeasureAudio15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15
; AverageSize=#Fluidity#

[MeterBar15]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio15

[MeasureAudio16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16
; AverageSize=#Fluidity#

[MeterBar16]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio16

[MeasureAudio17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17
; AverageSize=#Fluidity#

[MeterBar17]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio17

[MeasureAudio18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18
; AverageSize=#Fluidity#

[MeterBar18]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio18

[MeasureAudio19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19
; AverageSize=#Fluidity#

[MeterBar19]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio19

[MeasureAudio20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20
; AverageSize=#Fluidity#

[MeterBar20]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio20

[MeasureAudio21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=21
; AverageSize=#Fluidity#

[MeterBar21]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio21

[MeasureAudio22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=22
; AverageSize=#Fluidity#

[MeterBar22]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio22

[MeasureAudio23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=23
; AverageSize=#Fluidity#

[MeterBar23]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio23

[MeasureAudio24]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=24
; AverageSize=#Fluidity#

[MeterBar24]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio24

[MeasureAudio25]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=25
; AverageSize=#Fluidity#

[MeterBar25]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio25

[MeasureAudio26]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=26
; AverageSize=#Fluidity#

[MeterBar26]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio26

[MeasureAudio27]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=27
; AverageSize=#Fluidity#

[MeterBar27]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio27

[MeasureAudio28]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=28
; AverageSize=#Fluidity#

[MeterBar28]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio28

[MeasureAudio29]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=29
; AverageSize=#Fluidity#

[MeterBar29]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio29

[MeasureAudio30]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=30
; AverageSize=#Fluidity#

[MeterBar30]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio30

[MeasureAudio31]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=31
; AverageSize=#Fluidity#

[MeterBar31]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio31

[MeasureAudio32]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=32
; AverageSize=#Fluidity#

[MeterBar32]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio32

[MeasureAudio33]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=33
; AverageSize=#Fluidity#

[MeterBar33]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio33

[MeasureAudio34]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=34
; AverageSize=#Fluidity#

[MeterBar34]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio34

[MeasureAudio35]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=35
; AverageSize=#Fluidity#

[MeterBar35]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio35

[MeasureAudio36]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=36
; AverageSize=#Fluidity#

[MeterBar36]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio36

[MeasureAudio37]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=37
; AverageSize=#Fluidity#

[MeterBar37]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio37

[MeasureAudio38]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=38
; AverageSize=#Fluidity#

[MeterBar38]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio38

[MeasureAudio39]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=39
; AverageSize=#Fluidity#

[MeterBar39]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio39

[MeasureAudio40]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=40
; AverageSize=#Fluidity#

[MeterBar40]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio40

[MeasureAudio41]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=41
; AverageSize=#Fluidity#

[MeterBar41]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio41

[MeasureAudio42]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=42
; AverageSize=#Fluidity#

[MeterBar42]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio42

[MeasureAudio43]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=43
; AverageSize=#Fluidity#

[MeterBar43]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio43

[MeasureAudio44]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=44
; AverageSize=#Fluidity#

[MeterBar44]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio44

[MeasureAudio45]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=45
; AverageSize=#Fluidity#

[MeterBar45]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio45

[MeasureAudio46]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=46
; AverageSize=#Fluidity#

[MeterBar46]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio46

[MeasureAudio47]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=47
; AverageSize=#Fluidity#

[MeterBar47]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio47

[MeasureAudio48]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=48
; AverageSize=#Fluidity#

[MeterBar48]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio48

[MeasureAudio49]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=49
; AverageSize=#Fluidity#

[MeterBar49]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio49

[MeasureAudio50]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=50
; AverageSize=#Fluidity#

[MeterBar50]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio50

[MeasureAudio51]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=51
; AverageSize=#Fluidity#

[MeterBar51]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio51

[MeasureAudio52]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=52
; AverageSize=#Fluidity#

[MeterBar52]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio52

[MeasureAudio53]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=53
; AverageSize=#Fluidity#

[MeterBar53]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio53

[MeasureAudio54]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=54
; AverageSize=#Fluidity#

[MeterBar54]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio54

[MeasureAudio55]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=55
; AverageSize=#Fluidity#

[MeterBar55]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio55

[MeasureAudio56]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=56
; AverageSize=#Fluidity#

[MeterBar56]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio56

[MeasureAudio57]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=57
; AverageSize=#Fluidity#

[MeterBar57]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio57

[MeasureAudio58]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=58
; AverageSize=#Fluidity#

[MeterBar58]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio58

[MeasureAudio59]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=59
; AverageSize=#Fluidity#

[MeterBar59]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio59

[MeasureAudio60]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=60
; AverageSize=#Fluidity#

[MeterBar60]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio60

[MeasureAudio61]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=61
; AverageSize=#Fluidity#

[MeterBar61]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio61

[MeasureAudio62]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=62
; AverageSize=#Fluidity#

[MeterBar62]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio62

[MeasureAudio63]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=63
; AverageSize=#Fluidity#

[MeterBar63]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio63

[MeasureAudio64]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=64
; AverageSize=#Fluidity#

[MeterBar64]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio64

[MeasureAudio65]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=65
; AverageSize=#Fluidity#

[MeterBar65]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio65

[MeasureAudio66]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=66
; AverageSize=#Fluidity#

[MeterBar66]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio66

[MeasureAudio67]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=67
; AverageSize=#Fluidity#

[MeterBar67]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio67

[MeasureAudio68]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=68
; AverageSize=#Fluidity#

[MeterBar68]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio68

[MeasureAudio69]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=69
; AverageSize=#Fluidity#

[MeterBar69]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio69

[MeasureAudio70]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=70
; AverageSize=#Fluidity#

[MeterBar70]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio70

[MeasureAudio71]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=71
; AverageSize=#Fluidity#

[MeterBar71]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio71

[MeasureAudio72]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=72
; AverageSize=#Fluidity#

[MeterBar72]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio72

[MeasureAudio73]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=73
; AverageSize=#Fluidity#

[MeterBar73]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio73

[MeasureAudio74]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=74
; AverageSize=#Fluidity#

[MeterBar74]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio74

[MeasureAudio75]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=75
; AverageSize=#Fluidity#

[MeterBar75]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio75

[MeasureAudio76]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=76
; AverageSize=#Fluidity#

[MeterBar76]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio76

[MeasureAudio77]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=77
; AverageSize=#Fluidity#

[MeterBar77]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio77

[MeasureAudio78]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=78
; AverageSize=#Fluidity#

[MeterBar78]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio78

[MeasureAudio79]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=79
; AverageSize=#Fluidity#

[MeterBar79]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio79

[MeasureAudio80]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=80
; AverageSize=#Fluidity#

[MeterBar80]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio80

[MeasureAudio81]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=81
; AverageSize=#Fluidity#

[MeterBar81]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio81

[MeasureAudio82]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=82
; AverageSize=#Fluidity#

[MeterBar82]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio82

[MeasureAudio83]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=83
; AverageSize=#Fluidity#

[MeterBar83]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio83

[MeasureAudio84]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=84
; AverageSize=#Fluidity#

[MeterBar84]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio84

[MeasureAudio85]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=85
; AverageSize=#Fluidity#

[MeterBar85]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio85

[MeasureAudio86]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=86
; AverageSize=#Fluidity#

[MeterBar86]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio86

[MeasureAudio87]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=87
; AverageSize=#Fluidity#

[MeterBar87]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio87

[MeasureAudio88]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=88
; AverageSize=#Fluidity#

[MeterBar88]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio88

[MeasureAudio89]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=89
; AverageSize=#Fluidity#

[MeterBar89]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio89

[MeasureAudio90]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=90
; AverageSize=#Fluidity#

[MeterBar90]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio90

[MeasureAudio91]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=91
; AverageSize=#Fluidity#

[MeterBar91]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio91

[MeasureAudio92]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=92
; AverageSize=#Fluidity#

[MeterBar92]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio92

[MeasureAudio93]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=93
; AverageSize=#Fluidity#

[MeterBar93]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio93

[MeasureAudio94]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=94
; AverageSize=#Fluidity#

[MeterBar94]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio94

[MeasureAudio95]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=95
; AverageSize=#Fluidity#

[MeterBar95]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio95

[MeasureAudio96]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=96
; AverageSize=#Fluidity#

[MeterBar96]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio96

[MeasureAudio97]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=97
; AverageSize=#Fluidity#

[MeterBar97]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio97

[MeasureAudio98]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=98
; AverageSize=#Fluidity#

[MeterBar98]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio98

[MeasureAudio99]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=99
; AverageSize=#Fluidity#

[MeterBar99]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio99

[MeasureAudio100]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=100
; AverageSize=#Fluidity#

[MeterBar100]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio100

[MeasureAudio101]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=101
; AverageSize=#Fluidity#

[MeterBar101]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio101

[MeasureAudio102]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=102
; AverageSize=#Fluidity#

[MeterBar102]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio102

[MeasureAudio103]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=103
; AverageSize=#Fluidity#

[MeterBar103]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio103

[MeasureAudio104]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=104
; AverageSize=#Fluidity#

[MeterBar104]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio104

[MeasureAudio105]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=105
; AverageSize=#Fluidity#

[MeterBar105]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio105

[MeasureAudio106]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=106
; AverageSize=#Fluidity#

[MeterBar106]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio106

[MeasureAudio107]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=107
; AverageSize=#Fluidity#

[MeterBar107]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio107

[MeasureAudio108]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=108
; AverageSize=#Fluidity#

[MeterBar108]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio108

[MeasureAudio109]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=109
; AverageSize=#Fluidity#

[MeterBar109]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio109

[MeasureAudio110]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=110
; AverageSize=#Fluidity#

[MeterBar110]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio110

[MeasureAudio111]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=111
; AverageSize=#Fluidity#

[MeterBar111]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio111

[MeasureAudio112]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=112
; AverageSize=#Fluidity#

[MeterBar112]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio112

[MeasureAudio113]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=113
; AverageSize=#Fluidity#

[MeterBar113]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio113

[MeasureAudio114]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=114
; AverageSize=#Fluidity#

[MeterBar114]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio114

[MeasureAudio115]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=115
; AverageSize=#Fluidity#

[MeterBar115]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio115

[MeasureAudio116]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=116
; AverageSize=#Fluidity#

[MeterBar116]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio116

[MeasureAudio117]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=117
; AverageSize=#Fluidity#

[MeterBar117]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio117

[MeasureAudio118]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=118
; AverageSize=#Fluidity#

[MeterBar118]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio118

[MeasureAudio119]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=119
; AverageSize=#Fluidity#

[MeterBar119]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio119

[MeasureAudio120]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=120
; AverageSize=#Fluidity#

[MeterBar120]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio120

[MeasureAudio121]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=121
; AverageSize=#Fluidity#

[MeterBar121]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio121

[MeasureAudio122]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=122
; AverageSize=#Fluidity#

[MeterBar122]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio122

[MeasureAudio123]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=123
; AverageSize=#Fluidity#

[MeterBar123]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio123

[MeasureAudio124]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=124
; AverageSize=#Fluidity#

[MeterBar124]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio124

[MeasureAudio125]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=125
; AverageSize=#Fluidity#

[MeterBar125]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio125

[MeasureAudio126]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=126
; AverageSize=#Fluidity#

[MeterBar126]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio126

[MeasureAudio127]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=127
; AverageSize=#Fluidity#

[MeterBar127]
Meter=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio127